### ISSUE TITLE
`MangroveOrder.take` should accept an `offerId` to update a pre existing resting order

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove-core#145]
A clever frontend might want to recycle a previous resting order id from an offer maker. This would save gas and allow users to recycle their locked provision without needing to re finance a new resting order.

To do this we may want to check that the recycled offer id is not live. If it is not on Mangrove then a new offer is created (for instance if `offerId` is 0).

**Comment by lnist** [comment]
Fixed
