### ISSUE TITLE
Provide a hook to manage offer owner's remaining provision after a trade has failed

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove-core#149]
When an offer fails, offer owner's remaining provision is added to makerContract's balance on Mangrove. In the case of `Direct` strats, offer owner can redeem these funds using `withdrawFromMangrove` (admin restricted).
In the case of `Forwarder` strat, (an approximation of) these funds are being assigned to offer owner in `__posthookFallback__` hook. 
This is an issue because strat builders can override this hook and either forget to call `super` or call `super` early in the overridden hook and mess up the approximation.

To remediate for this I suggest the following:
1/ `makerExecute` of `MangroveOffer` calls `__handleResidualProvision__(order)` **right after the posthookFallback hook**.

1. We provide a default implementation of the hook as a noop by default.
3/ in `Forwarder` we implement the hook with the current implementation of the `__posthookFallback__`, i.e:

```solidity
function __handleResidualProvision__(MgvLib.SingleOrder memory order) internal override {
   mapping(uint => OwnerData) storage semiBookOwnerData =
      ownerData[IERC20(order.outbound_tkn)][IERC20(order.inbound_tkn)];
    // NB if several offers of `this` contract have failed during the market order, the balance of this contract on Mangrove will contain cumulated free provision

    // computing an under approximation of returned provision because of this offer's failure
    uint gasreq = order.offerDetail.gasreq();
    uint provision = 10 ** 9 * order.offerDetail.gasprice() * (gasreq + order.offerDetail.offer_gasbase());

    // gasUsed estimate to complete posthook and penalize this offer is ~1750 (empirical estimate)
    uint gasprice = order.global.gasprice() * 10 ** 9;
    uint approxGasConsumption = gasreq + GAS_APPROX + order.local.offer_gasbase();
    uint approxBounty = (approxGasConsumption - gasleft()) * gasprice;
    uint approxReturnedProvision = approxBounty >= provision ? 0 : provision - approxBounty;

    // storing the portion of this contract's balance on Mangrove that should be attributed back to the failing offer's owner
    // those free WEIs can be retrieved by offer owner, by calling `retractOffer` with the `deprovision` flag.
    semiBookOwnerData[order.offerId].weiBalance += uint96(approxReturnedProvision);
}
```

**Comment by lnist** [comment]
This was fixed by https://github.com/mangrovedao/mangrove-core/pull/150
