### ISSUE TITLE
`MgvReader` should implement a `view` function that gives a volume and gas estimate for a market order

### ISSUE THREAD

**Issue by jkrivine** [mangrovedao/mangrove-core#25]
In order to enable on-chain order routing, we would like to have a function that gives a volume estimate for a given market order.
For instance 
```solidity 
(uint estimateReceive, uint estimateGas) = mgvReader.estimateOutbound(outbound, inbound, takerGives, fillWants);
```
or
```solidity
(uint estimateSend, uint estimateGas) = mgvReader.estimateInbound(outbound, inbound, takerWants, fillWants);
```

**Comment by jkrivine** [comment]
An interesting point is that in the sequence:
```solidity
(uint estimateReceive, uint estimateGas) = mgvReader.estimateOutbound(outbound, inbound, takerGives, false);
mgv.marketOrder(outbound, inbound, estimateReceive, takerGives, false);
```
the part of the market order that accesses the list of offers is in hot storage. Thus a part of the gas cost of running the estimate would be compensated by the lower gas cost of the market order (would need to check experimentally whether this is true)

A more advanced version of `estimateOut/Inbound` would take as an argument an array of increasing volumes, (e.g. `[10,100,1000]`) and return an array of estimates (e.g `[est_10, est_100, est_1000]`). This would allow an onchain order splitter to call mangrove for a part of the original order only.

**Comment by adhusson** [comment]
After looking at this I don't think it will work by running a market order, then reverting, due to a detail of [EIP-2929](https://eips.ethereum.org/EIPS/eip-2929) (emphasis mine):
> The sets are transaction-context-wide, implemented identically to other transaction-scoped constructs such as the self-destruct-list and global refund counter. In particular, **if a scope reverts, the access lists should be in the state they were in before that scope was entered.**

So there is no gas reduction associated with running a market order, getting the volume info out, then reverting.

I will look at a more manual way of doing it.
