### ISSUE TITLE
Natspec IMangrove, MgvReader, MgvCleaner

### ISSUE THREAD

**Issue by lnist** [mangrovedao/mangrove-core#251]
**Is your feature request related to a problem? Please describe.**
The core protocol functions are not documented in an easily consumable format for strat writers, and ditto for the two important periphery contracts. MgvOracle is not as important, but could be included.

**Describe the solution you'd like**
Since the core protocol uses a custom doc format, then we can instead document the above thoroughly to get it aligned with the rest of the doc. For strat writers the functions in the interface is probably more important than the internal workings of the protocol.

Also, consider making all tests go through the IMangrove interface so that we verify that it conforms to the protocol.

**Comment by dontrolle** [comment]
As discussed, this has already been done.
