### ISSUE TITLE
Make Mangrove easy to use through a wrapper contract

### ISSUE THREAD

**Issue by adhusson** [mangrovedao/mangrove-core#478]
Having wrappers around Mangrove for the following would be useful:
* Additional API functions
* Simple offer management

The idea is that the core contract does not change but extra functionality can be added by evolving wrappers.

This is easier if users can go through the wrapper without additional `approve` transactions or such, or a minimal amount.

Permit2 (#420) could be a good starting point for a wrapper flow that doesn't use extra transactions. Another approach could be signature-based: the wrapper receives an order&a signature, and does 2 calls to Mangrove (one to submit the signature, the other to run the order).

Analysis : https://www.notion.so/mangroveexchange/Permit2-integration-with-Mangrove-b6d520d35f2a41d7aaf3b7a137d20c48?pvs=4

**Comment by espendk** [comment]
I think the Permit2 functionality that will be added to MangroveOrder in https://github.com/mangrovedao/mangrove-strats/pull/13 demonstrates that wrappers are possible as-is.

So maybe we can close this? @adhusson

**Comment by adhusson** [comment]
Yes, agreed
