### ISSUE TITLE
Big ticks renaming

### ISSUE THREAD

**Issue by adhusson** [mangrovedao/mangrove-core#562]
Heavily paraphrasing @espendk 's writeup:

* `price` becomes `ratio`: a ratio [inbound]/[outbound] at which a taker/maker is willing to trade
* `tick` becomes `tickTreeIndex`
* `logRatio` becomes `tick`: an index into the discrete range  ]0; ∞[ of logs of ratios that contains 1 and with `ratio_tick / ratio_{tick-1} = 1 + tickSize`

  * This still keeps market terminology distinct from offer list terminology. Tick is a known term, both from trading generally and from Uniswap

* `ratio = (1+tickSize)^tick`
* `tick = log_{1+tickSize}(ratio)`  when `log_{1+tickSize}(ratio) % 1 == 0`
* `tickSize` is 1bps (0.0001): the minimum, relative ratio movement in an offer list
* `tickSpacing` : an offer list parameter that defines the spacing between valid ticks for that offer list: `tick % tickSpacing == 0`.
* `tickTreeIndex`: a number that uniquely identifies the the position in the tick tree where the offers for a tick is stored for a given tickSpacing
* `tickTreeIndex = tick/tickSpacing`

Slack discussion link https://mangroveitops.slack.com/archives/C05LDSH7FHD/p1694526478940409

**Comment by adhusson** [comment]
Closed by efcf853f7486a3f713c19bf15369665ea4794167

**Comment by espendk** [comment]
For the record and easy later reference, we ended up with this slightly modified terminology:

* `price` becomes `ratio`: a ratio [inbound]/[outbound] at which a taker/maker is willing to trade
* `tick` becomes `bin`
* `logRatio` becomes `tick`: an index into the discrete range  ]0; ∞[ of logs of ratios that contains 1 and with `ratio_tick / ratio_{tick-1} = 1 + tickSize`

  * This still keeps market terminology distinct from offer list terminology. Tick is a known term, both from trading generally and from Uniswap

* `ratio = (1+tickSize)^tick`
* `tick = log_{1+tickSize}(ratio)`  when `log_{1+tickSize}(ratio) % 1 == 0`
* `tickSize` is 1bps (0.0001): the minimum, relative ratio movement in an offer list
* `tickSpacing` : an offer list parameter that defines the spacing between valid ticks for that offer list: `tick % tickSpacing == 0`.
* `bin`: a number that uniquely identifies the position in the tick tree where the offers for a tick is stored for a given tickSpacing
* `bin = tick/tickSpacing`  when  `tick % tickSpacing == 0`
